{% set name = "django-nested-admin" %}
{% set version = "3.0.21" %}
{% set build = 0 %}
{% set sha256 = "e0868d3e97b12007f65bd5c216b69e841e796938376b5751309094904907aa65" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/theatlantic/django-nested-admin/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - python-monkey-business >=1.0.0

  run:
    - python
    - django
    - python-monkey-business >=1.0.0

test:
  imports:
    - nested_admin
    - nested_admin.templatetags
    - nested_admin.tests
    - nested_admin.tests.admin_widgets
    - nested_admin.tests.gfk
    - nested_admin.tests.one_deep
    - nested_admin.tests.three_deep
    - nested_admin.tests.two_deep

about:
  home: https://github.com/theatlantic/django-nested-admin
  license: BSD 2-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Django admin classes that allow for nested inlines
  dev_url: https://github.com/theatlantic/django-nested-admin
  doc_url: https://github.com/theatlantic/django-nested-admin


extra:
  recipe-maintainers:
    - kwilcox
