{% set version = "3.3.2" %}

package:
  name: django-nested-admin
  version: {{ version }}

source:
  url: https://github.com/theatlantic/django-nested-admin/archive/v{{ version }}.tar.gz
  sha256: 035a763cf41a857967d24bcce722c9cc9e009a903ccd9163ca60e74f6022f92b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
    - python-monkey-business >=1.0.0
  run:
    - python
    - django
    - python-monkey-business >=1.0.0

test:
  imports:
    - nested_admin
    - nested_admin.templatetags
    - nested_admin.tests
    - nested_admin.tests.admin_widgets
    - nested_admin.tests.gfk
    - nested_admin.tests.one_deep
    - nested_admin.tests.three_deep
    - nested_admin.tests.two_deep

about:
  home: https://github.com/theatlantic/django-nested-admin
  license: BSD 2-Clause
  license_file: LICENSE
  license_family: BSD
  summary: Django admin classes that allow for nested inlines
  dev_url: https://github.com/theatlantic/django-nested-admin
  doc_url: https://github.com/theatlantic/django-nested-admin


extra:
  recipe-maintainers:
    - kwilcox
